### PR TITLE
Added StopWatch

### PR DESCRIPTION
**Pull request by charandeep7**
I have added stopwatch with all the features mentioned.
Pls review and approve. #39 

Uploading StopwatchVideo.mp4…

### CODE REVIEW

**Review by SandeepKrSuman — CHANGES_REQUESTED** [review]
Great work @charandeep7 ! 

Your front-end is nice. However, the functionality is that of a **TIMER** rather than a **Stop Watch**.
Also stop watch is already added in #25 . 

You have made a nice project and I look forward to add this in the gallery. 
Here's few changes that you are supposed to do:
- replace the word 'stop watch' with **Timer** everywhere in the project
- while capturing the gif, make sure only the project part is visible. Currently whole chrome window is visible which gives it a bad look while creating the thumbnail for the gallery. 
You may use this gif recorder: https://www.screentogif.com/

_**Kindly do the required changes and I'll review to merge this PR.**_

**Comment by charandeep7** [comment]
@SandeepKrSuman 
I've made the changes you requested for. 
Can you please label as Hacktoberfest 
please review and approved. 
#40

**Comment by SandeepKrSuman** [comment]
I cannot find any changes in this PR. Kindly push the changes if you have made them locally. 

PS.: hacktoberfest label will be added only after approval.

**Comment by SandeepKrSuman** [comment]
Screenshot (655)

See above, your last commit was 4 hours ago and there's no changes after that.

**Comment by charandeep7** [comment]
@SandeepKrSuman Sorry, for the inconvenience sir. Please review it again. 
#40

**Review by SandeepKrSuman — APPROVED** [review]
Looks good to me 🚀

**Pull request merged**
