### PR TITLE
Added a Qr Reader

### LINKED ISSUE #68: QR Code Reader
A basic QR Code Reader using HTML CSS and Javascript. 
Which can distinguish between QR and image. 
Please consider it under Hacktoberfest.

### PR DESCRIPTION
**Pull request by radzhiv25**
close #68

### CODE REVIEW

**Review by SandeepKrSuman — APPROVED** [review]
Hi, if you can add some sample qr files to scan that would really be nice. I tried with some from my end and it was unable to scan any of them. Everything else seems fine to me 👍

**Comment by radzhiv25** [comment]
> Hi, if you can add some sample qr files to scan that would really be nice. I tried with some from my end and it was unable to scan any of them. Everything else seems fine to me 👍

 

Ok

**Comment by SandeepKrSuman** [comment]
Just put them inside your folder (same place where index.html exists)
Do this one commit and I'll merge. Thanks!

**Review by SandeepKrSuman — APPROVED** [review]

**Comment by radzhiv25** [comment]
When will the status update

**Comment by SandeepKrSuman** [comment]
Hey @radzhiv25 as a project maintainer our task is only to maintain the repos well and merge valid PR's with `hactoberfest-accepted` label. It is upto hacktoberfest to verify and update the status in background and **we have no control over that whatsoever**. Thanks!

**Pull request merged**
